server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}       # 1 hora
  refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:30}      # 30 dias

aws:
  endpoint: ${AWS_ENDPOINT:}
  public-endpoint: ${AWS_PUBLIC_ENDPOINT:${AWS_ENDPOINT:}}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket:
      profile-assets: ${S3_PROFILE_ASSETS_BUCKET:profile-assets}

logging:
  level:
    root: INFO
