server:
  port: ${PORT:8084}

spring:
  application:
    name: group-service
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}

aws:
  endpoint: ${AWS_ENDPOINT:}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket:
      config: ${S3_CONFIG_BUCKET:upfit-config}
      group-assets: ${S3_GROUP_ASSETS_BUCKET:group-assets}

sqs:
  queue:
    group-url: ${SQS_GROUP_QUEUE_URL}

sns:
  topic:
    notification-arn: ${NOTIFICATION_TOPIC_ARN}

logging:
  level:
    root: INFO
    br.com.upfit: INFO
