events {
    worker_connections 1024;
}

http {

    # ─── Upstreams ────────────────────────────────────────────────────────────────
    upstream auth-service         { server auth-service:8081; }
    upstream workout-service      { server workout-service:8082; }
    upstream progression-service  { server progression-service:8083; }
    upstream group-service        { server group-service:8084; }
    upstream challenge-service    { server challenge-service:8085; }
    upstream notification-service { server notification-service:8086; }

    server {
        listen 8080;

        # ─── Roteamento por path ──────────────────────────────────────────────────

        location /auth/ {
            proxy_pass         http://auth-service/auth/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /profile {
            proxy_pass         http://auth-service/profile;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /workouts/ {
            proxy_pass         http://workout-service/workouts/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /progression/ {
            proxy_pass         http://progression-service/progression/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /achievements/ {
            proxy_pass         http://progression-service/achievements/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /groups/ {
            proxy_pass         http://group-service/groups/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /challenges/ {
            proxy_pass         http://challenge-service/challenges/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /notifications/ {
            proxy_pass         http://notification-service/notifications/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }
    }
}
